In [13]:
import pandas as pd   # importamos una libreria pandas 

#crear un diccionario, metemos datos crudos manualmente
data = {
    "nombre": ["ana", "juan", "pedro"],
    "edad": [23, 35, 28],
    "ciudad": ["madrid", "bogota", "cdmx"],
    'fecha': ['01/01/2024 09:00', '2024-01-01 10:00:00', 'Error_Date']
}

df = pd.DataFrame(data)    # variable dataframe que almacena la tabla de datos
# pd.DataFrame(datos)  funcion que crea una tabla de datos
print(df)

df.to_csv('primeroPrueba.csv', index = False)    
df1 = pd.read_csv('primeroPrueba.csv')
display(df1)  
df1.info()

# LIMPIEZA
    #1. LIMPIEZA DE FEHAS
# cojo columna fechas y la limpio de errores entregando objetos tipo DATETIME
df1['fecha'] = pd.to_datetime(df1['fecha'], errors = "coerce")
display(df1)  # para mostrar fecha corregida

    #2. LIMPIEZA DE DATOS
# convertir numeros en texto 
df1['edad'] = pd.to_numeric(df1['edad'], errors = "coerce")
display(df1)

  nombre  edad  ciudad                fecha
0    ana    23  madrid     01/01/2024 09:00
1   juan    35  bogota  2024-01-01 10:00:00
2  pedro    28    cdmx           Error_Date

  nombre  edad  ciudad                fecha
0    ana    23  madrid     01/01/2024 09:00
1   juan    35  bogota  2024-01-01 10:00:00
2  pedro    28    cdmx           Error_Date

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  3 non-null      str
 1   edad    3 non-null      int64
 2   ciudad  3 non-null      str
 3   fecha   3 non-null      str
dtypes: int64(1), str(3)
memory usage: 228.0 bytes

  nombre  edad  ciudad               fecha
0    ana    23  madrid 2024-01-01 09:00:00
1   juan    35  bogota                 NaT
2  pedro    28    cdmx                 NaT

  nombre  edad  ciudad               fecha
0    ana    23  madrid 2024-01-01 09:00:00
1   juan    35  bogota                 NaT
2  pedro    28    cdmx                 NaT